### ISSUE TITLE
Expand README. 

### ISSUE THREAD

**Issue by carltongibson** [django/django-asv#17]
So one checkouts, installs the requirements, `asv run`, ... — then what? 

* We should probably point to the ASV docs, and mention `publish`/`preview`. 
* Plus maybe how to generate a few runs for (e.g.) daily commits for last week, weekly commits for last month? (So there's something to see). 

Plus, also, a little about the project, and how to join in. 

Related is the discussion on the forum about the `results` folder: https://forum.djangoproject.com/t/django-benchmarking-project/13887/11 — Can we commit this back to the repo (and accept PRs maybe) so that we can build up the data over time? 

I would **think** that running once a day (or week even once we've got some data) is more than enough to spot regressions no? 

(Thoughts? 🤔 — We're working out the answers.)

**Comment by smithdc1** [comment]
I agree with all of Carlton's comments. 

Scipy has a separate repo[1] which stores the results, and an action [2] to build and publish the pages. Note: I'm not entirely sure where the script for the actions are saved. 

[1] https://github.com/pv/scipy-bench
[2] https://github.com/pv/scipy-bench/actions

I think it is reasonable to store the results in this repo (scipy's benchmarks are in its main repo i.e there equivalent to django/django) and build the output here too.

I did some work with the aim of running a benchmark and committing the results back to the repo a while back. Some of these steps may be useful here, but likely there is a better way since I wrote this a couple of years ago. 
 https://github.com/smithdc1/djangobench-tracker/blob/main/.github/workflows/django-commits.yml

It could be two actions. One to run the benchmarks as a cron job and another to build and publish the pages on each commit. That way we can accept prs with others results in future. 

Likely running it in GHA will be noisy. I'm not familiar with self hosted runners but presumably it will be the same workflow just run on our own infrastructure 🤔.

**Comment by carltongibson** [comment]
> Likely running it in GHA will be noisy. I'm not familiar with self hosted runners but presumably it will be the same workflow just run on our own infrastructure 🤔

Yes, we need to investigate. 

My thought though is to just get it up with the hosted runner and have a look. (Maybe that's enough, maybe it's easier to see what the requirements are from there, maybe weekly hosted with some uploads from … is enough to smooth the noise, ... — etc.) — either wa we should be able to block out what we need initially on the hosted runners. 

(I haven't heard back from Ops yet: other things going on. But to the extent we can **pull** from an untrusted environment, rather than **push** with a token of some kind into a trusted environment, the happier they'll be, I imagine.)

**Comment by carltongibson** [comment]
Also, locally I had good success generating runs for particular commits, and ranges, so it's not a biggie if we need to rebuild results later on.

**Comment by smithdc1** [comment]
On a similar note I had success with giving a list of commits (in a text file iirc). So maybe we could generate a list of those and create a one off script to run the first commit of each month for the past X (5?) years say. That way we can build up some history and see some longer term trends.

**Comment by smithdc1** [comment]
Hey @deepakdinesh1123 -- What's your thoughts on this? (No rush, just wanted to check it's on your radar 📡 )

**Comment by deepakdinesh1123** [comment]
I am sorry I did not reply earlier, I was working on this for the past couple of days, and here is the progress I was able to make

- Locally, I was able to generate results for the first commit of each month for the past 5 years and I am running actions on my fork to automate the benchmarking and publishing part
- After a few sample workflow runs where I tried to commit to the `results` folder itself, I think keeping the results folder ignored is better as running the benchmarks on branches can affect it and the results might get affected.
- The results can be published and viewed by copying the `asv.conf.json` file to `ci-results` folder and running the `asv publish`

I will update the README as soon as I am done with the workflows, I am currently working on setting up a workflow to generate the result for the commits for the past 5 years and push it to the repository.

**Comment by smithdc1** [comment]
No need to apologies, you are doing great work. 🙏 

> ...  I am running actions on my fork to automate the benchmarking and publishing part

Great stuff, looking forward to seeing this. 🎉 

> ... running the benchmarks on branches can affect it and the results might get affected.

I don't quite understand this, could you explain further please?

**Comment by deepakdinesh1123** [comment]
> the results might get affected

- ASV saves information about the machine, so if the results of the benchmarks from another machine are added, the results cannot be published and the results will be corrupted.
- Removing results from gitignore in just a branch also had problems as the results from runs in other branches showed up as changes in that branch

I have added the workflows to run the benchmarks every day and I have also added the workflow I used to generate the results of the commits for the past 5 years, since the `publish-results` workflow depended on a `workflow_run` event I added it to the main branch of my fork, I will make the necessary changes and create a PR from another branch and move the HEAD of main

[benchmark results and static files](https://github.com/deepakdinesh1123/django-asv/tree/main/ci-results)
[workflows](https://github.com/deepakdinesh1123/django-asv/tree/main/.github/workflows)

Since the machine name changes between actions I have given the machine name as `INTEL`, I will change it later. If there are no other changes I will update the `README`

I am also looking at Buildbot and Jenkins to run the benchmarks when a pull request is labeled, I will update its status as soon as I can.

**Comment by carltongibson** [comment]
> ASV saves information about the machine, so if the results of the benchmarks from another machine are added, the results cannot be published and the results will be corrupted.

Hmmm 🤔 
I thought the idea was to both be able to filter by and average over different machines. 
Maybe a bit of investigation? (I may be entirely wrong 😃)

**Comment by carltongibson** [comment]
From [the docs](https://asv.readthedocs.io/en/stable/using.html#benchmarking): 

> The results are stored as JSON files in the directory results/$MACHINE, where $MACHINE is the unique machine name that was set up in your ~/.asv-machine.json file.

And locally: 

<img width="912" alt="Screenshot 2022-06-09 at 11 25 22" src="https://user-images.githubusercontent.com/64686/172814337-c39767be-d56f-4b23-9a36-a1cd2129b5c1.png">

So, can we add results to the correct `$MACHINE` subdirectory, and add _How to do that_ to the README? 🤔

**Comment by deepakdinesh1123** [comment]
![Screenshot from 2022-06-09 21-40-37](https://user-images.githubusercontent.com/52698821/172994060-c4c17dfc-c6bc-475c-9552-a063d7cbf06b.png)

![Screenshot from 2022-06-09 21-36-02](https://user-images.githubusercontent.com/52698821/172994066-66f57f8b-7a18-452b-981b-09c35ca92dfd.png)

These were the results I was able to obtain while using multiple machines, is this what you were hoping to see?
Should I change the `benchmark.yml ` workflow to run on different operating systems and add those results to their respective directories in `ci-results`?

**Comment by smithdc1** [comment]
> These were the results I was able to obtain while using multiple machines, is this what you were hoping to see?

These screenshots look nice. 👌 

This is was I was expecting to see, you can the slice the data by machine and see them all at once. And _maybe_ in the future by Python version too. 

Maybe there's still some work to see how many machine names we get from running it in CI (are they unique every time?), but maybe that can be improved with a self hosted runner. 

> Should I change the `benchmark.yml ` workflow to run on different operating systems and add those results to their respective directories in `ci-results`? 

Could you explain this further. I'm not sure I'm familiar with either of `benchmark.yml` or `ci-results` (why is this different to the results folder in Carlton's image).

I wonder if it may help my understanding and the discussion if you could open a PR with the current changes? 🤔

**Comment by carltongibson** [comment]
I think closed by #59 for now.
